# Nama file: .github/ISSUE_TEMPLATE/feature-request.yml

name: ✨ Permintaan Fitur Baru
description: Sarankan sebuah ide atau fitur baru untuk proyek ini.
title: "[FITUR] <Judul fitur yang singkat>"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Terima kasih atas saran Anda! Mohon isi formulir di bawah ini.
  - type: textarea
    id: problem
    attributes:
      label: Apakah fitur ini berhubungan dengan suatu masalah?
      description: |
        Jelaskan masalah yang ingin Anda selesaikan. 
        Contoh: "Saya sulit melacak progres saya karena tidak ada halaman dashboard."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Jelaskan solusi yang Anda usulkan
      description: Jelaskan bagaimana fitur baru ini akan menyelesaikan masalah di atas.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Apakah ada alternatif lain yang sudah Anda pertimbangkan?
      description: Jelaskan solusi atau cara lain yang mungkin bisa dilakukan.
  - type: markdown
    attributes:
      value: "Terima kasih telah mengajukan permintaan fitur ini!"
